name: publish

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Build page
        run: pnpm run build
      - name: Upload built project output
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
      - name: Upload to SFTP
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: pnpm run sftp
